final Map<String, List<String>> pueblosTuristicos=
//List<Map<String, List<String>>> pueblosTuristicos = [
  {
    'Argentina': ['Bariloche', 'El Calafate', 'Puerto Iguazú'],
    'Australia': ['Byron Bay', 'Port Douglas', 'Magnetic Island'],
    'Austria': ['Hallstatt', 'Salzburgo', 'Zell am See'],
    'Bélgica': ['Brujas', 'Gante', 'Durbuy'],
    'Brasil': ['Paraty', 'Gramado', 'Ouro Preto'],
    'Canadá': ['Banff', 'Whistler', 'Tofino'],
    'Chile': ['Valparaíso', 'Puerto Varas', 'Pucón'],
    'China': ['Lijiang', 'Pingyao', 'Fenghuang'],
    'Colombia': ['Villa de Leyva', 'Salento', 'Guatapé'],
    'Costa Rica': ['Monteverde', 'La Fortuna', 'Manuel Antonio'],
    'Croacia': ['Dubrovnik', 'Rovinj', 'Trogir'],
    'Ecuador': ['Baños', 'Montañita', 'Cuenca'],
    'Escocia': ['Edimburgo', 'Stirling', 'Inverness'],
    'España': ['Toledo', 'Ronda', 'Cadaqués'],
    'Estados Unidos': ['Sedona', 'Aspen', 'Key West'],
    'Francia': ['Annecy', 'Colmar', 'Riquewihr'],
    'Grecia': ['Santorini', 'Meteora', 'Nafplio'],
    'Holanda': ['Giethoorn', 'Volendam', 'Edam'],
    'Indonesia': ['Ubud', 'Yogyakarta', 'Bromo'],
    'Inglaterra': ['Bath', 'York', 'Oxford'],
    'Irlanda': ['Kilkenny', 'Galway', 'Dingle'],
    'Italia': ['Cinque Terre', 'Positano', 'San Gimignano'],
    'Japón': ['Takayama', 'Shirakawa-go', 'Nara'],
    'México': ['San Miguel de Allende', 'Guanajuato', 'Tulum'],
    'Noruega': ['Bergen', 'Tromsø', 'Stavanger'],
    'Nueva Zelanda': ['Queenstown', 'Rotorua', 'Akaroa'],
    'Perú': ['Arequipa', 'Cusco', 'Pisac'],
    'Portugal': ['Sintra', 'Óbidos', 'Lisboa'],
    'Rumania': ['Sibiu', 'Sighisoara', 'Brasov'],
    'Suiza': ['Zermatt', 'Interlaken', 'Lauterbrunnen'],
    'Tailandia': ['Chiang Mai', 'Ayutthaya', 'Pai'],
    'Turquía': ['Estambul', 'Cappadocia', 'Ephesus'],
    'Uruguay': ['Colonia del Sacramento', 'Punta del Este', 'Cabo Polonio'],
    'Vietnam': ['Hoi An', 'Sapa', 'Hue'],
  };
